homepage: "https://github.com/go-gitea/gitea"
primary_contact: "security@gitea.io"
auto_ccs :
  - "xiaolunwen@gmail.com"
  - "techknowlogick@gitea.io"
  - "zeripath@gmail.com"
  - "john.olheiser@gmail.com"
  - "the6543dev@gmail.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/go-gitea/gitea"
